# Generated by Django 5.1.2 on 2024-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermodule', '0002_address2_student2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
    ]
