# Generated by Django 5.1.2 on 2024-10-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0001_initial'),
    ]

    operations = [
    ]
