# Generated by Django 5.1.2 on 2024-12-01 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmodule', '0003_address_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
